package org.ihtsdo.otf.mapping.jpa.handlers;

/**
 * This code was auto-generated by apg.
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 */

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Stack;

/**
 * Parser for map rule clauses.
 */
public class MapRuleParser {

  /** The Constant END_MARKER. */
  private static final int END_MARKER = 256;

  /** The Constant MIN_RULE_ID. */
  private static final int MIN_RULE_ID = END_MARKER + 1;

  /** The goto table. */
  private CompressedMatrix<Integer> gotoTable;

  /** The action table. */
  private CompressedMatrix<Action> actionTable;

  /** The reverse dfas. */
  private Dfa[] reverseDfas;

  /**
   * Instantiates an empty {@link MapRuleParser}.
   */
  public MapRuleParser() {
    this.gotoTable =
        new CompressedMatrix<>(new Integer[] {
            4, 5, 5, 17, 18, 19, 17, 23, 24, 29, 31, 35, 39, 37, 41, 42, 37,
            41, 47, 51, 53, 58, 59, 58, 64, 69, 71, 72, 73, 74, 75, 76, 77, 79,
        }, new int[] {
            0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 7, 8, 9, 9,
            10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 12, 12, 14, 15, 16, 16, 17,
            17, 17, 17, 18, 19, 19, 20, 20, 20, 21, 21, 21, 21, 21, 22, 23, 23,
            23, 23, 23, 24, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 28,
            29, 30, 31, 32, 33, 34,
        }, new int[] {
            258, 259, 260, 263, 264, 268, 261, 265, 268, 262, 268, 268, 266,
            268, 269, 268, 268, 269, 268, 267, 268, 270, 268, 270, 268, 268,
            268, 268, 268, 268, 268, 268, 268, 268,
        });
    this.actionTable =
        new CompressedMatrix<>(new Action[] {
            new Action(ActionType.Shift, 1), new Action(ActionType.Shift, 2),
            new Action(ActionType.Shift, 3), new Action(ActionType.Shift, 6),
            new Action(ActionType.Shift, 7), new Action(ActionType.Shift, 8),
            new Action(ActionType.Accept, 0),
            new Action(ActionType.Reduce, 258),
            new Action(ActionType.Shift, 10), new Action(ActionType.Shift, 11),
            new Action(ActionType.Shift, 12),
            new Action(ActionType.Reduce, 257),
            new Action(ActionType.Shift, 13), new Action(ActionType.Shift, 14),
            new Action(ActionType.Shift, 15), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 20),
            new Action(ActionType.Reduce, 260),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Shift, 21),
            new Action(ActionType.Reduce, 259),
            new Action(ActionType.Shift, 22), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 25),
            new Action(ActionType.Shift, 26), new Action(ActionType.Shift, 27),
            new Action(ActionType.Shift, 28), new Action(ActionType.Shift, 30),
            new Action(ActionType.Reduce, 263),
            new Action(ActionType.Reduce, 263),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 32),
            new Action(ActionType.Reduce, 262),
            new Action(ActionType.Shift, 27),
            new Action(ActionType.Reduce, 262),
            new Action(ActionType.Reduce, 262),
            new Action(ActionType.Shift, 27), new Action(ActionType.Shift, 33),
            new Action(ActionType.Shift, 34), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 36),
            new Action(ActionType.Shift, 37), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 16),
            new Action(ActionType.Shift, 16), new Action(ActionType.Shift, 43),
            new Action(ActionType.Reduce, 266),
            new Action(ActionType.Shift, 37), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38), new Action(ActionType.Shift, 38),
            new Action(ActionType.Shift, 38),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Shift, 44),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 45),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 40), new Action(ActionType.Shift, 40),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 48), new Action(ActionType.Shift, 49),
            new Action(ActionType.Shift, 50),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Shift, 52),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 269),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 54), new Action(ActionType.Shift, 55),
            new Action(ActionType.Shift, 56),
            new Action(ActionType.Reduce, 261),
            new Action(ActionType.Reduce, 261),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 60), new Action(ActionType.Shift, 61),
            new Action(ActionType.Shift, 62),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Reduce, 270),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 63),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Shift, 57), new Action(ActionType.Shift, 57),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 65),
            new Action(ActionType.Reduce, 267),
            new Action(ActionType.Shift, 66),
            new Action(ActionType.Reduce, 267),
            new Action(ActionType.Shift, 67), new Action(ActionType.Shift, 68),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 15),
            new Action(ActionType.Reduce, 267),
            new Action(ActionType.Reduce, 267),
            new Action(ActionType.Reduce, 267),
            new Action(ActionType.Shift, 66),
            new Action(ActionType.Reduce, 267),
            new Action(ActionType.Shift, 70),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Reduce, 265),
            new Action(ActionType.Reduce, 265),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Shift, 46), new Action(ActionType.Shift, 46),
            new Action(ActionType.Reduce, 264),
            new Action(ActionType.Shift, 78), new Action(ActionType.Shift, 78),
            new Action(ActionType.Shift, 78), new Action(ActionType.Shift, 78),
            new Action(ActionType.Shift, 78), new Action(ActionType.Shift, 78),
            new Action(ActionType.Shift, 78), new Action(ActionType.Shift, 78),
            new Action(ActionType.Shift, 78), new Action(ActionType.Shift, 78),
            new Action(ActionType.Reduce, 268),
            new Action(ActionType.Reduce, 264),
        }, new int[] {
            0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 25, 26, 27, 37, 39,
            40, 50, 51, 54, 55, 57, 67, 68, 70, 71, 73, 74, 75, 85, 86, 97,
            221, 231, 232, 244, 256, 257, 381, 505, 515, 516, 518, 643, 654,
            665, 666, 667, 668, 670, 723, 734, 735, 736, 737, 791, 845, 856,
            857, 860, 861, 862, 873, 874, 876, 879, 880, 891, 893, 904, 915,
            926, 937, 948, 959, 970, 971, 972,
        }, new int[] {
            73, 79, 84, 70, 84, 82, 256, 256, 65, 72, 85, 256, 32, 69, 69, 48,
            49, 50, 51, 52, 53, 54, 55, 56, 57, 82, 256, 48, 49, 50, 51, 52,
            53, 54, 55, 56, 57, 32, 256, 32, 48, 49, 50, 51, 52, 53, 54, 55,
            56, 57, 87, 60, 61, 62, 124, 32, 256, 48, 49, 50, 51, 52, 53, 54,
            55, 56, 57, 73, 32, 61, 32, 32, 61, 32, 32, 48, 49, 50, 51, 52, 53,
            54, 55, 56, 57, 83, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 1,
            2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
            21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
            38, 39, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
            57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
            74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
            91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105,
            106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
            119, 120, 121, 122, 123, 125, 126, 127, 48, 49, 50, 51, 52, 53, 54,
            55, 56, 57, 69, 32, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 32,
            46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 32, 1, 2, 3, 4, 5, 6,
            7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
            24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42,
            43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
            60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
            77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
            94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
            108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
            121, 122, 123, 125, 126, 127, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
            12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
            29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43, 44, 45, 46, 47,
            48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
            65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
            82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
            99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
            112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 125,
            126, 127, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 32, 100, 121, 1,
            2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
            21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
            38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
            56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
            73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
            90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104,
            105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
            118, 119, 120, 121, 122, 123, 125, 126, 127, 32, 48, 49, 50, 51,
            52, 53, 54, 55, 56, 57, 32, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
            84, 97, 101, 32, 256, 32, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
            75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 97,
            98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
            112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 32, 48, 49,
            50, 51, 52, 53, 54, 55, 56, 57, 82, 121, 97, 32, 41, 65, 66, 67,
            68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
            85, 86, 87, 88, 89, 90, 97, 98, 99, 100, 101, 102, 103, 104, 105,
            106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
            119, 120, 121, 122, 32, 41, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
            75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 97,
            98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
            112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 32, 48, 49,
            50, 51, 52, 53, 54, 55, 56, 57, 85, 32, 115, 256, 114, 32, 32, 48,
            49, 50, 51, 52, 53, 54, 55, 56, 57, 69, 32, 256, 32, 115, 256, 124,
            32, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 32, 256, 32, 48, 49,
            50, 51, 52, 53, 54, 55, 56, 57, 32, 48, 49, 50, 51, 52, 53, 54, 55,
            56, 57, 32, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 32, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 32, 48, 49, 50, 51, 52, 53, 54, 55, 56,
            57, 32, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 32, 48, 49, 50, 51,
            52, 53, 54, 55, 56, 57, 32, 32,
        });
    this.reverseDfas =
        new Dfa[] {
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 2,
            }, new int[] {
                0, 1, 2,
            }, new int[] {
                256, 258,
            }), new int[] {
              2,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 1,
            }, new int[] {
                0, 2,
            }, new int[] {
                259, 260,
            }), new int[] {
              1,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                0, 1, 2, 3, 4, 5,
            }, new int[] {
                0, 2, 3, 4, 5, 6,
            }, new int[] {
                261, 263, 32, 65, 70, 73,
            }), new int[] {
              5,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
            }, new int[] {
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
            }, new int[] {
                69, 85, 82, 84, 32, 69, 83, 73, 87, 82, 69, 72, 84, 79,
            }), new int[] {
                4, 14,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 2, 3, 4, 5, 6,
            }, new int[] {
                0, 1, 2, 3, 4, 5, 6,
            }, new int[] {
                267, 32, 266, 32, 262, 32,
            }), new int[] {
              6,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 2, 1, 1, 1,
            }, new int[] {
                0, 3, 3, 5,
            }, new int[] {
                60, 61, 62, 60, 62,
            }), new int[] {
                1, 2,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 2,
            }, new int[] {
                0, 1, 2,
            }, new int[] {
                265, 264,
            }), new int[] {
              2,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            }, new int[] {
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                18,
            }, new int[] {
                268, 268, 268, 268, 268, 268, 268, 268, 268, 268, 268, 268,
                268, 268, 268, 268, 268, 268,
            }), new int[] {
                6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 2, 3, 4, 5, 4, 6, 7, 8, 7, 9, 10,
            }, new int[] {
                0, 1, 2, 3, 4, 6, 7, 8, 10, 11, 12,
            }, new int[] {
                124, 32, 41, 270, 40, 270, 32, 269, 32, 269, 124, 32,
            }), new int[] {
              10,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 1, 1, 1,
            }, new int[] {
                0, 2, 4,
            }, new int[] {
                46, 268, 46, 268,
            }), new int[] {
              1,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 11, 11,
            }, new int[] {
                0, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 14, 15,
            }, new int[] {
                114, 115, 121, 97, 114, 121, 97, 101, 97, 97, 100, 121, 101,
                100, 121,
            }), new int[] {
              11,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            }, new int[] {
                0, 10,
            }, new int[] {
                48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
            }), new int[] {
              1,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            }, new int[] {
                0, 124,
            }, new int[] {
                1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
                19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
                35, 36, 37, 38, 39, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
                53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
                69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
                85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99,
                100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
                112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
                125, 126, 127,
            }), new int[] {
              1,
            }),
            new Dfa(new CompressedMatrix<>(new Integer[] {
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            }, new int[] {
                0, 53,
            }, new int[] {
                32, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
                80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 97, 98, 99, 100,
                101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
                113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
            }), new int[] {
              1,
            }),
        };
  }

  /**
   * Parses the.
   *
   * @param stream the stream
   * @return true, if successful
   * @throws IOException Signals that an I/O exception has occurred.
   */
  public boolean parse(InputStream stream) throws IOException {
    boolean isMatch = false;

    Stack<Integer> stateStack = new Stack<>();
    Stack<Integer> inputStack = new Stack<>();
    stateStack.push(0);

    int c = stream.read();
    if (c == -1) {
      c = END_MARKER;
    }

    while (true) {
      Action action = this.actionTable.get(stateStack.peek(), c);

      if (action == null) {
        isMatch = false;
        break;
      } else if (action.type() == ActionType.Shift) {
        stateStack.push(action.state());
        inputStack.push(c);

        c = stream.read();
        if (c == -1) {
          c = END_MARKER;
        }
      } else if (action.type() == ActionType.Reduce) {
        Dfa fa = this.reverseDfas[action.ruleId() - MIN_RULE_ID];
        fa.setState(0);

        Integer[] input = inputStack.toArray(new Integer[] {});
        int lastMatchIndex = input.length;

        for (int i = input.length - 1; i >= 0 && fa.step(input[i]); i--) {
          if (fa.isMatch()) {
            lastMatchIndex = i;
          }
        }

        for (int i = input.length - 1; i >= lastMatchIndex; i--) {
          inputStack.pop();
          stateStack.pop();
        }

        stateStack.push(this.gotoTable.get(stateStack.peek(), action.ruleId()));
        inputStack.push(action.ruleId());
      } else if (action.type() == ActionType.Accept) {
        isMatch = true;
        break;
      } else {
        throw new IllegalStateException();
      }
    }

    return isMatch;
  }

  /**
   * Represents a parser action.
   */
  private class Action {

    /** The type. */
    private ActionType type;

    /** The data. */
    private int data;

    /**
     * Instantiates a {@link Action} from the specified parameters.
     *
     * @param type the type
     * @param data the data
     */
    public Action(ActionType type, int data) {
      this.type = type;
      this.data = data;
    }

    /**
     * Type.
     *
     * @return the action type
     */
    public ActionType type() {
      return this.type;
    }

    /**
     * Rule id.
     *
     * @return the int
     */
    public int ruleId() {
      return this.data;
    }

    /**
     * State.
     *
     * @return the int
     */
    public int state() {
      return this.data;
    }
  }

  /**
   * The action type enum.
   */
  private enum ActionType {

    /** The Shift. */
    Shift,
    /** The Reduce. */
    Reduce,
    /** The Accept. */
    Accept,
    /** The Error. */
    Error
  }

  /**
   * The Class Dfa.
   */
  private class Dfa {

    /** The transition table. */
    private CompressedMatrix<Integer> transitionTable;

    /** The accept states. */
    private int[] acceptStates;

    /** The state. */
    private int state;

    /**
     * Instantiates a {@link Dfa} from the specified parameters.
     *
     * @param transitionTable the transition table
     * @param acceptStates the accept states
     */
    public Dfa(CompressedMatrix<Integer> transitionTable, int[] acceptStates) {
      this.transitionTable = transitionTable;
      this.acceptStates = acceptStates;
      this.state = 0;
    }

    /**
     * Sets the state.
     *
     * @param state the state
     */
    public void setState(int state) {
      this.state = state;
    }

    /**
     * Indicates whether or not match is the case.
     *
     * @return <code>true</code> if so, <code>false</code> otherwise
     */
    public boolean isMatch() {
      int start = 0;
      int end = this.acceptStates.length;
      int mid = start + (end - start) / 2;

      while (start < end) {
        if (this.state < this.acceptStates[mid]) {
          end = mid;
          mid = start + (end - start) / 2;
        } else if (this.state > this.acceptStates[mid]) {
          start = mid + 1;
          mid = start + (end - start) / 2;
        } else {
          break;
        }
      }

      return this.state == this.acceptStates[mid];
    }

    /**
     * Step.
     *
     * @param character the character
     * @return true, if successful
     */
    public boolean step(int character) {
      Integer newState = this.transitionTable.get(this.state, character);

      if (newState == null) {
        return false;
      }

      this.state = newState;
      return true;
    }
  }

  /**
   * The Class CompressedMatrix.
   * @param <T> the
   */
  private class CompressedMatrix<T> {

    /** The a. */
    private T[] a;

    /** The ia. */
    private int[] ia;

    /** The ja. */
    private int[] ja;

    /**
     * Instantiates a {@link CompressedMatrix} from the specified parameters.
     *
     * @param a the a
     * @param ia the ia
     * @param ja the ja
     */
    public CompressedMatrix(T[] a, int[] ia, int[] ja) {
      this.a = a;
      this.ia = ia;
      this.ja = ja;
    }

    /**
     * Returns the.
     *
     * @param x the x
     * @param y the y
     * @return the t
     */
    public T get(int x, int y) {
      if (x >= this.ia.length - 1) {
        return null;
      }

      int start = this.ia[x];
      int end = this.ia[x + 1];
      int mid = start + (end - start) / 2;

      while (start < end) {
        if (y < this.ja[mid]) {
          end = mid;
          mid = start + (end - start) / 2;
        } else if (y > this.ja[mid]) {
          start = mid + 1;
          mid = start + (end - start) / 2;
        } else {
          break;
        }
      }

      return y == this.ja[mid] ? this.a[mid] : null;
    }
  }

  /**
   * Application entry point - test patterns with this.
   *
   * @param args the command line arguments
   * @throws IOException Signals that an I/O exception has occurred.
   */
  public static void main(String[] args) throws IOException {

    MapRuleParser parser = new MapRuleParser();

    try {
      BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
      String line;
      while ((line = in.readLine()) != null) {
        boolean isMatch =
            parser.parse(new ByteArrayInputStream(line.getBytes()));

        System.out.println(String.format("Is '%1$s' a valid map rule?", line));
        System.out.println(isMatch ? "Yes" : "No");

        String[] tokens = line.split(" AND ");
        for (String token : tokens) {
          System.out.println("." + token + ".");
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

}