#!/bin/sh -e

#For debugging uncomment these two lines
#set -x
#echo $*

APP_NAME=[[packageName]]

vardirs="run logs data/ihtsdo-project-data"

dir=/var/opt/$APP_NAME
test -d $dir || mkdir -p $dir && chmod 700 $dir && chown $APP_NAME $dir

for d in $vardirs
do
  dir=/var/opt/$APP_NAME/$d
  test -d $dir || mkdir -p $dir && chmod 700 $dir && chown $APP_NAME $dir
done

test -e /var/log/$APP_NAME || ln -s /var/opt/$APP_NAME/logs /var/log/$APP_NAME

status=$( supervisorctl status $APP_NAME | awk '{print $2}' )

case $status in
  RUNNING)
    supervisorctl update $APP_NAME | grep updated || supervisorctl restart $APP_NAME
    ;;
  STOPPED)
    supervisorctl update $APP_NAME | grep updated && supervisorctl stop $APP_NAME
    ;;
  such)
    # 'No such process'
    supervisorctl update $APP_NAME
    ;;
esac
