#!/bin/sh -e

#For debugging uncomment these two lines
#set -x
#echo $*

APP_NAME=[[packageName]]

case $1 in
	purge)
		if getent passwd $APP_NAME >/dev/null; then
  			userdel $APP_NAME
		fi
		if test -d /var/opt/$APP_NAME; then
			rm -r /var/opt/$APP_NAME
		fi
	    if test -d /opt/tomcat8/indexes; then
			rm -rf /opt/tomcat8/indexes
		fi
	;;
esac
