startrule = TruthStatement / Clause *AdditionalClause
AdditionalClause = " AND " Clause
Clause = "IFA " ConceptAny
TruthStatement = "TRUE" / "OTHERWISE TRUE"
Value = NumericOperator " " Numeric " " TimePeriod
NumericOperator = "=" / "<" / ">" / "<=" / ">="
ConceptAny = SctId FullySpecifiedName
SctId = 6*18(DIGIT)
FullySpecifiedName = " | " *(CHAR) " (" 1*(ALPHA) ") |"
Numeric = 1*(DIGIT/".")
TimePeriod = "day"/"days"/"year"/"years"
DIGIT = %x30-39
CHAR = %x01-27/%x2A-7B/%x7D-7F
ALPHA = %x41-5A/%x61-7A/" "
